gitlab-server:
  ports:
  - ${ssh_port}:22/tcp
  - ${http_port}:80/tcp
  - ${https_port}:443/tcp
  hostname: ${gitlab_hostname}
  image: gitlab/gitlab-ce:latest
  volume_driver: rancher-nfs
  volumes:
  - ${storage_prefix}-etc:/etc/gitlab
  - ${storage_prefix}-log:/var/log/gitlab
  - ${storage_prefix}-opt:/var/opt/gitlab
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url '${gitlab_omnipus_prefix}${gitlab_hostname}'
