gitlab-server:
  ports:
  - ${ssh_port}:22/tcp
  - ${http_port}:80/tcp
  - ${https_port}:443/tcp
  labels:
    io.rancher.sidekicks: gitlab-data
  hostname: ${gitlab_hostname}
  image: gitlab/gitlab-ce:latest
  volume_driver: rancher-nfs
  volumes_from:
  - gitlab-data
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url '${gitlab_omnipus_prefix}${gitlab_hostname}'

gitlab-data:
  labels:
    io.rancher.container.start_once: 'true'
  entrypoint:
  - /bin/true
  hostname: gitdata
  image: gitlab/gitlab-ce:latest
  volume_driver: rancher-nfs
  volumes:
  - gitlab-etc:/etc/gitlab
  - gitlab-log:/var/log/gitlab
  - gitlab-opt:/var/opt/gitlab

